#!/usr/bin/env python
import argparse
import sys
from pathlib import Path

TEMPLATE = """import React from "react";
import { {icon} } from "lucide-react";

type {name}Props = {{
  title?: string;
  value?: string | number;
  subtitle?: string;
}};

export default function {name}({{ title = "{name}", value = "—", subtitle = "Generated by scaffold_ui" }}: {name}Props) {{
  return (
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#0f172a] transition-colors">
      <div className="flex items-center gap-3 border-b border-slate-100 px-4 py-3 text-slate-600 dark:border-slate-800 dark:text-slate-200">
        <span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-200">
          <{icon} className="h-5 w-5" />
        </span>
        <div className="flex flex-col">
          <span className="text-sm font-semibold">{ '{' }title{ '}' }</span>
          <span className="text-xs text-slate-400">{ '{' }subtitle{ '}' }</span>
        </div>
      </div>
      <div className="px-4 py-6 text-3xl font-bold text-slate-900 dark:text-white">{ '{' }value{ '}' }</div>
    </section>
  );
}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a React TSX component with DL styling.")
    parser.add_argument("ComponentName", help="Name of the component to create (e.g., StatCard)")
    parser.add_argument("--out", default="dlcs-ui/src/components", help="Output directory (default: dlcs-ui/src/components)")
    parser.add_argument("--icon", default="Sparkles", help="lucide-react icon to use (default: Sparkles)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing file")
    args = parser.parse_args()

    name = args.ComponentName
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    outfile = out_dir / f"{name}.tsx"
    if outfile.exists() and not args.force:
        print(f"{outfile} already exists. Use --force to overwrite.")
        return 1

    content = TEMPLATE.format(name=name, icon=args.icon)
    outfile.write_text(content)
    print(f"Created component scaffold at {outfile}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
